
<TopBar>:
    title: 'GPS TrackMe'
    elevation: 10
    
    ToolbarIcon:
        icon: "map-marker-check"
        on_release: root.btn_track()
    
    ToolbarIcon:
        icon: root.icon_accuracy
    
    ToolbarIcon:
        icon: root.icon_gps
        on_release: root.btn_gps()
    
    ToolbarIcon:
        id: menu
        icon: "dots-vertical"
        on_release: root.btn_menu()
 

<ToolbarIcon>:
    theme_text_color: 'Custom'
    text_color: 1,1,1,1


